name: mony_manager
description: "تطبيق إدارة مالية متكامل"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  # ✅ تم إضافته
    sdk: flutter  
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  path_provider: ^2.1.5
  path: ^1.9.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  fl_chart: ^1.0.0
  auto_size_text: ^3.0.0
  
    
  intl: ^0.20.2
  crypto: ^3.0.6
  country_code_picker: ^3.3.0
  syncfusion_flutter_charts: ^29.1.41
  uuid: ^4.2.1

  # Firebase Authentication
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.4
  # Add Cloud Firestore
  cloud_firestore: ^4.15.5
  # Add Firebase Storage
  firebase_storage: ^11.6.6
  google_fonts: ^6.3.2
  timezone: ^0.10.1
  flutter_local_notifications: ^19.4.2
  connectivity_plus: ^7.0.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  flutter_localization: ^0.2.1
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/images/google_logo.png
    - lib/images/download.png
